### ISSUE TITLE
capture example does not compile

### ISSUE THREAD

**Issue by djadala** [gen2brain/malgo#12]
```
go run _examples/capture/capture.go
# command-line-arguments
_examples/capture/capture.go:25:14: deviceConfig.Format undefined (type malgo.DeviceConfig has no field or method Format)
_examples/capture/capture.go:26:14: deviceConfig.Channels undefined (type malgo.DeviceConfig has no field or method Channels)
_examples/capture/capture.go:34:60: deviceConfig.Format undefined (type malgo.DeviceConfig has no field or method Format)
_examples/capture/capture.go:36:43: deviceConfig.Channels undefined (type malgo.DeviceConfig has no field or method Channels)
_examples/capture/capture.go:47:3: unknown field 'Recv' in struct literal of type malgo.DeviceCallbacks
_examples/capture/capture.go:49:33: too many arguments in call to malgo.InitDevice
	have (malgo.Context, malgo.DeviceType, nil, malgo.DeviceConfig, malgo.DeviceCallbacks)
	want (malgo.Context, malgo.DeviceConfig, malgo.DeviceCallbacks)
_examples/capture/capture.go:67:45: deviceConfig.Channels undefined (type malgo.DeviceConfig has no field or method Channels)
_examples/capture/capture.go:76:38: deviceConfig.Channels undefined (type malgo.DeviceConfig has no field or method Channels)
_examples/capture/capture.go:81:3: unknown field 'Send' in struct literal of type malgo.DeviceCallbacks
_examples/capture/capture.go:84:32: too many arguments in call to malgo.InitDevice
	have (malgo.Context, malgo.DeviceType, nil, malgo.DeviceConfig, malgo.DeviceCallbacks)
	want (malgo.Context, malgo.DeviceConfig, malgo.DeviceCallbacks)
_examples/capture/capture.go:84:32: too many errors
```

**Comment by danfletcher1** [comment]
Do you want to try these changes.

// This example simply captures data from your default microphone until you press Enter, after which it plays back the captured audio.
package main

import (
	"fmt"
	"os"

	"github.com/gen2brain/malgo"
)

func main() {
	ctx, err := malgo.InitContext(nil, malgo.ContextConfig{}, func(message string) {
		fmt.Printf("LOG <%v>\n", message)
	})
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
	defer func() {
		_ = ctx.Uninit()
		ctx.Free()
	}()

	deviceConfig := malgo.DefaultDeviceConfig()
	deviceConfig.DeviceType = 3
	deviceConfig.Capture.Format = malgo.FormatS16
	deviceConfig.Capture.Channels = 1
	deviceConfig.Playback.Format = malgo.FormatS16
	deviceConfig.Playback.Channels = 1
	deviceConfig.SampleRate = 8000
	deviceConfig.Alsa.NoMMap = 1

	var playbackSampleCount uint32
	var capturedSampleCount uint32
	pCapturedSamples := make([]byte, 0)

	sizeInBytes := uint32(malgo.SampleSizeInBytes(deviceConfig.Capture.Format))
	onRecvFrames := func(pSample2, pSample []byte, framecount uint32) {

		sampleCount := framecount * deviceConfig.Capture.Channels * sizeInBytes

		newCapturedSampleCount := capturedSampleCount + sampleCount

		pCapturedSamples = append(pCapturedSamples, pSample...)

		capturedSampleCount = newCapturedSampleCount

	}

	fmt.Println("Recording...")
	captureCallbacks := malgo.DeviceCallbacks{
		Data: onRecvFrames,
	}
	device, err := malgo.InitDevice(ctx.Context, deviceConfig, captureCallbacks)
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}

	err = device.Start()
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}

	fmt.Println("Press Enter to stop recording...")
	fmt.Scanln()

	device.Uninit()

	onSendFrames := func(pSample, nil []byte, framecount uint32) {
		samplesToRead := framecount * deviceConfig.Playback.Channels * sizeInBytes
		if samplesToRead > capturedSampleCount-playbackSampleCount {
			samplesToRead = capturedSampleCount - playbackSampleCount
		}

		copy(pSample, pCapturedSamples[playbackSampleCount:playbackSampleCount+samplesToRead])

		playbackSampleCount += samplesToRead

		if playbackSampleCount == uint32(len(pCapturedSamples)) {
			playbackSampleCount = 0
		}
	}

	fmt.Println("Playing...")
	playbackCallbacks := malgo.DeviceCallbacks{
		Data: onSendFrames,
	}

	device, err = malgo.InitDevice(ctx.Context, deviceConfig, playbackCallbacks)
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}

	err = device.Start()
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}

	fmt.Println("Press Enter to quit...")
	fmt.Scanln()

	device.Uninit()
}

**Comment by djadala** [comment]
Thank you (Хвала ?). 
At least it compile, i test it later when i have mic ...
may be ```s/deviceConfig.DeviceType = 3/deviceConfig.DeviceType = malgo.Duplex/``` ?

**Comment by djadala** [comment]
Yes, it works,
can i afford to recommend some style ?
```
s/
nSendFrames := func(pSample, nil []byte, framecount uint32) {
/
nSendFrames := func(pSample, _ []byte, framecount uint32) {
/

s/
onRecvFrames := func(pSample2, pSample []byte, framecount uint32) {
/
onRecvFrames := func(_, pSample []byte, framecount uint32) {
/
```

**Comment by danfletcher1** [comment]
Appreciate the feedback. I did remember to remove the pSample2 before
posting the pull request, but I never though to use _ for nil. Thanks for
the tip.

**Comment by djadala** [comment]
actually nil here is variable name:
https://play.golang.org/p/yGW0r-fc3_K

**Comment by danfletcher1** [comment]
Oh yes, so it is. 
I tried 'true', 'error', '5' also. Good clarification of the language. 
As expected 5 is 5, but the reserved keywords of true/nil/error will become variable name, and true will no longer mean true.

**Comment by egonelbre** [comment]
This should be fixed currently.
