### ISSUE TITLE
Doesn't work with go mod?

### ISSUE THREAD

**Issue by tylerlong** [gen2brain/malgo#14]
```
microphone-demo export GO111MODULE=off
➜  microphone-demo go get -u github.com/gen2brain/malgo
➜  microphone-demo export GO111MODULE=on
➜  microphone-demo go get -u github.com/gen2brain/malgo
go: finding github.com/gen2brain/malgo latest
# github.com/gen2brain/malgo
In file included from ../../../../pkg/mod/github.com/gen2brain/malgo@v0.0.0-20191007143048-89d560b7cba5/context.go:3:
./malgo.h:4:10: fatal error: 'miniaudio/miniaudio.h' file not found
#include "miniaudio/miniaudio.h"
         ^~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
➜  microphone-demo
```

You can see that with `go mod` enabled, I cannot install this package at all. It installs without go mod.

**Comment by gen2brain** [comment]
The reason is probably miniaudio repo that was added recently as a git submodule. `go get` will fetch submodule, but `go mod` doesn't do that step. It should be added as was before, just miniaudio.h in root dir in order to work with modules.

**Comment by gonearewe** [comment]
Also, you may 'git clone'  miniaudio by yourself and add the folder to the root dir where you may find a empty folder called  'miniaudio' in your case.

**Comment by gen2brain** [comment]
This is now fixed.
