### ISSUE TITLE
Examples not compiled

### ISSUE THREAD

**Issue by gonearewe** [gen2brain/malgo#15]
Hi there, I run into some problems while trying to compile the examples.
Error Reports:

<pre>
$ go run ./_examples/playback/playback.go ./track01.mp3
# command-line-arguments
_examples/playback/playback.go:74:14: deviceConfig.Format undefined (type malgo.DeviceConfig has no field or method Format)
_examples/playback/playback.go:75:14: deviceConfig.Channels undefined (type malgo.DeviceConfig has no field or method Channels)
_examples/playback/playback.go:79:59: deviceConfig.Format undefined (type malgo.DeviceConfig has no field or method Format)
_examples/playback/playback.go:87:3: unknown field 'Send' in struct literal of type malgo.DeviceCallbacks
_examples/playback/playback.go:89:33: too many arguments in call to malgo.InitDevice
        have (malgo.Context, malgo.DeviceType, nil, malgo.DeviceConfig, malgo.DeviceCallbacks)
        want (malgo.Context, malgo.DeviceConfig, malgo.DeviceCallbacks)
</pre>

It seems that  examples don't match the code. I'm not sure...  may the examples remain unchanged after updating?

**Comment by etx** [comment]
Same here

**Comment by etx** [comment]
@gonearewe Fix is pretty simple, see this PR: https://github.com/gen2brain/malgo/pull/16/commits/bce5f7719abf1b6bee05e28d13c334ffde5e7730

**Comment by gen2brain** [comment]
Fixed by @etx in https://github.com/gen2brain/malgo/commit/bce5f7719abf1b6bee05e28d13c334ffde5e7730 .
