### ISSUE TITLE
How can I select a device to use for capture/playback manually?

### ISSUE THREAD

**Issue by fbrozovic** [gen2brain/malgo#23]
Simply passing a pointer to the ID obtained from `context.Devices` doesn't work, as it always panics at runtime with `panic: runtime error: cgo argument has Go pointer to Go pointer`. Is there a way to do this?

**Comment by gen2brain** [comment]
Passing ID to what? You should not use DefaultDeviceConfig but create custom DeviceConfig instead, which should contain ID from context.Devices you want to use. I had some examples where I needed that, but cannot find it, though, it should not be difficult.

**Comment by fbrozovic** [comment]
Sorry, I realized I could have been clearer with explaining how I'm trying to do this.

This is my attempt now, but I'm still getting the same error... I'm not really familiar with Cgo, so any help would be much appreciated.

```
...

infos, err := ctx.Devices(malgo.Duplex)
if err != nil {
	fmt.Println(err)
	os.Exit(1)
}

fmt.Println("Duplex devices")
for i, info := range infos {
	fmt.Printf("%d: %v, %s\n", i, info.ID, info.Name())
}
fmt.Println()

devConf1 := malgo.DeviceConfig {
	DeviceType: malgo.Duplex,
	SampleRate: 44100,
	Capture: malgo.SubConfig{
		DeviceID: &infos[0].ID,
		Format: malgo.FormatS16,
		Channels: 1,
	},
	Playback: malgo.SubConfig{
		DeviceID: &infos[0].ID,
		Format: malgo.FormatS16,
		Channels: 1,
	},
}

...

dev1, err := malgo.InitDevice(ctx.Context, devConf1, devCallbacks1)
if err != nil {
	fmt.Println(err)
	os.Exit(1)
}

...
```

**Comment by gen2brain** [comment]
Ok, need to check and test, API was different.

**Comment by fbrozovic** [comment]
Have you had a chance to look at this yet?

**Comment by gen2brain** [comment]
No, didn't find time to check.

**Comment by i0x71** [comment]
I am having the same issue, will post here if i can get it to work.

**Comment by gen2brain** [comment]
It should be fixed in https://github.com/gen2brain/malgo/commit/1b98196694de081425aacdf94d88df044674c484 , just pass `DeviceID: infos[0].ID.Pointer()` or whatever index of device.

@fbrozovic No need to free anything in this case, it is not allocated from Go, whatever you allocate in C from Go should be freed.
