### ISSUE TITLE
Documentation issue for InitDevice

### ISSUE THREAD

**Issue by jhelberg** [gen2brain/malgo#27]
The formal parameters of InitDevice list: context Context, deviceConfig DeviceConfig, deviceCallbacks DeviceCallbacks but the documentation says: The device ID can be nil, in which c...
There is no device ID in the parameterlist. It would be nice if there was, as I cannot select a specific device now with InitDevice.
Can the documention be in-line with the parameters?
Can you explain how to init a specific device, given it's device ID?

**Comment by gen2brain** [comment]
See https://github.com/gen2brain/malgo/issues/23.

**Comment by jhelberg** [comment]
thanks for explaining. Documentation will improve by writing:
'The deviceID in DeviceConfig.Capture or DeviceConfig.Playback can be nil, in which c...'
