### ISSUE TITLE
Microphone Not Working on built and notarized binary - MacOS

### ISSUE THREAD

**Issue by louistb** [gen2brain/malgo#35]
Hi, 

I am fairly new to go and just made a little binary to pipe the microphone sound to the google speech to text cloud API, it works fine when i do a go run of the code. It also works when i build on my mac machine. 

But once i build and notarized the binary to send it to someone in a zip, the microphone input recording don't seem to work when they run the app.

Am i missing something ? Should i be able to build and expect all the included binaries of the plugin to work on the build ?

i feel like it could be related to macOS microphone permission, when i launch the binary there is no prompt to give access to the microphone.

Thanks ❤️

**Comment by gen2brain** [comment]
No idea, I don't use macOS, but shouldn't you package your binary in a .app directory if you want to distribute it, then you can use a metadata/plist file like this described here https://developer.apple.com/documentation/avfoundation/cameras_and_media_capture/requesting_authorization_for_media_capture_on_macos.

**Comment by gen2brain** [comment]
Btw. miniaudio is a single header library, that uses runtime linking where possible, so you don't have to include "binaries of the plugin", everything is already in the binary. Frameworks that are used are CoreFoundation, CoreAudio, and AudioUnit.

**Comment by louistb** [comment]
Ok thanks for the info, i tried packing a manual .app with no success. 

Its for a single user for a specific interactive installation, i was just hoping to be able to make a simple binary that i could share that could use the microphone.

I will try to pack a .app again.

Or i will just setup golang on the person computer and do go run instead.

Thanks

**Comment by gen2brain** [comment]
Well, go run or go build is the same. Did you maybe use a root/admin account? Did you try to reset mic permissions with the command mentioned above, so it asks again for permissions?

**Comment by louistb** [comment]
I can confirm that running : `tccutil reset Microphone` did not fix the issue
Quick FYI is use : https://github.com/mitchellh/gon to sign and notarize the binary

I will try to build a .app manually, i hope i can get it to work this way at this point i would need to redo it in swift or in xcode i guess

**Comment by gen2brain** [comment]
This is documented in miniaudio https://miniaud.io/docs/manual/#Building.
