### ISSUE TITLE
NULL Audio device on MacOS 14.1.1 (23B81)

### ISSUE THREAD

**Issue by chiefMarlin** [gen2brain/malgo#48]
Hey,
I just noticed that on latest MacOS 14.1.1 (23B81) audio devices no longer show up correctly, only 2 devices available are as below:

# enumeration % go run enumeration.go               
Playback Devices
    0: 00, NULL Playback Device, [ok], formats: [{Format:0 Channels:0 SampleRate:0 Flags:0}]

Capture Devices
    0: 00, NULL Capture Device, [ok], formats: [{Format:0 Channels:0 SampleRate:0 Flags:0}]

It used to work fine on MacOS before, but i cant recall what the last working MacOS version was.
@gen2brain

**Comment by chiefMarlin** [comment]
I just tried using latest release of miniaudio from: https://github.com/mackron/miniaudio/releases/tag/0.11.21
And that seems to fix the issue. Please update [miniaudio.h](https://github.com/gen2brain/malgo/blob/master/miniaudio.h) when you can.

**Comment by mokiat** [comment]
I was just having a look at this library and noticed the same (on Linux it worked fine).

I tried running with `GOARCH=amd64`, thinking that it might be due to the arm processor, and hoping that it would be routed through rosetta, but then the code does not compile at all, so not an option it appears.

**Comment by chiefMarlin** [comment]
> I was just having a look at this library and noticed the same (on Linux it worked fine).
> 
> **NOTE:** I tried it on MacOS 14.1.2 and also on 13.?.? (I upgraded my OS hoping it would fix the issue) but does not work on both.
> 
> I tried running with `GOARCH=amd64`, thinking that it might be due to the arm processor, and hoping that it would be routed through rosetta, but then the code does not compile at all, so not an option it appears.

Until the PR gets accepted you can use my fork here: https://github.com/chiefMarlin/malgo
Thats what im using at the moment and its working.
