### ISSUE TITLE
Use sndio on OpenBSD

### ISSUE THREAD

**Issue by benpye** [gen2brain/malgo#6]
This library apparently uses OSS on OpenBSD currently, this seems unnessecary. The underlying library supports sndio which is OpenBSDs native audio library. Switching to sndio would mean this would have no additional dependencies on OpenBSD. I believe audio(4) would be preferably on NetBSD also.

**Comment by gen2brain** [comment]
Fixed in https://github.com/gen2brain/malgo/commit/c79ff816a6a39a25fef7427d6ae82f963db908c9 .
