### ISSUE TITLE
wails build -platform windows/amd64 ERROR

### ISSUE THREAD

**Issue by twowb** [gen2brain/malgo#61]
The error is as follows

# Building target: windows/amd64

  • Generating bindings: Done.
  • Installing frontend dependencies: Done.
  • Compiling frontend: Done.
  • Generating application assets: Done.
  • Compiling application: # changeme
./app.go:24:22: undefined: malgo.AllocatedContext
./app.go:25:21: undefined: malgo.DeviceConfig
./app.go:40:25: undefined: malgo.InitContext
./app.go:40:48: undefined: malgo.ContextConfig
./app.go:45:25: undefined: malgo.DefaultDeviceConfig
./app.go:61:28: undefined: malgo.DeviceCallbacks
./app.go:66:23: undefined: malgo.InitDevice

But there are no issues with Linux compilation

**Comment by gen2brain** [comment]
Nothing to do with this repo. You are compiling `cgo` project with `CGO_ENABLED=0`. When you correct this to `CGO_ENABLED=1`, you will see the real error, and it should be related to you trying to cross-compile the go project with the wrong C compiler. Every `cgo` project is like that. I have no idea what `wails build` is doing, though.

**Comment by twowb** [comment]
gcc: error: unrecognized command-line option ‘-mthreads’; did you mean ‘-pthread’?

**Comment by gen2brain** [comment]
As I said, now you see real error. You are trying to compile for Windows using a Linux C compiler.

**Comment by twowb** [comment]
必须在windows上进行编译是吗？但是我使用windows虚拟机编译，还是会有错误

**Comment by gen2brain** [comment]
Of course you can cross-compile, install mingw and use that instead of your compiler. It doesn't work in VM because you probably didn't install gcc there right? See e.g. here https://github.com/gen2brain/iup-go?tab=readme-ov-file#cross-compile-linux, you can also use `zig cc`, probably clang, lots of options.

**Comment by martinarisk** [comment]
To fix the problem:

**Step 1:** Install mingw (optional - if making exe on Linux)

```
sudo apt install mingw-w64
```

**Step 2:** go build

```
export GOOS=windows; export GOARCH=amd64; export CGO_ENABLED=1; export CXX=x86_64-w64-mingw32-g++; export CC=x86_64-w64-mingw32-gcc ; go build
```

**Done: Enjoy the exe**
