### ISSUE TITLE
Odd behavior after periodically capturing audio over a long period of time

### ISSUE THREAD

**Issue by howdoicomputer** [gen2brain/malgo#7]
Hey! This ain't so much an 'error' but a general usage type of question.

So I wrote a program that is kind of based off of the [capture](https://github.com/gen2brain/malgo/blob/master/_examples/capture/capture.go) example but using a timer. The source of that program is more or less [here](https://github.com/howdoicomputer/onair/blob/master/mike.go).

The parameters I'm passing into malgo look like this:

```
[Mike]
pollDuration = 5 // Every five seconds, capture one second of audio.
channels     = 1
sampleRate   = 8000
NoMMap       = 1
bufferSize   = 1000
```

Now, the application runs fine and it does exactly what I want it to do - which is to continuously detect whether or not my microphone is capturing audio. However, after probably, like, a few hours of running I start seeing problems from the perspective of other applications. If another application tries to grab control of the mic, then that application freezes up. This occurs even after I shut down my own application.

Is this some sort of locking issues? Am I doing something grossly inefficient? The platform I'm on is Windows 10.

Any and all help is super appreciated.

**Comment by gen2brain** [comment]
Hi,

If you build with `-tags mal_debug` you can get more info about the lock. You can also try to force one of `WASAPI, DirectSound, WinMM` and see what is different.

Also, current mini_al.h is not up to date with upstream, maybe it was a bug with mini_al that is already solved, with more info you can maybe also ask fo help there.

**Comment by mackron** [comment]
I think that diagnostic message is actually a bug in mini_al which I fixed a while ago: https://github.com/dr-soft/mini_al/commit/80e07775e274f9a36ce533c09527b0ab9553f98f. I'm pretty sure it actually is using DirectSound.

**Comment by gen2brain** [comment]
@howdoicomputer mini_al is updated to v0.8.14, update lib/repo and try now.

**Comment by howdoicomputer** [comment]
@gen2brain Thank you so much! I'm going to see if that between the version update and my code changes if the problem is fixed.

**Comment by howdoicomputer** [comment]
@gen2brain The problem has gone away. I think it might have been more that I was reinitializing context and the device every five seconds.
