### ISSUE TITLE
Plan to update to Miniaudio v0.9.1?

### ISSUE THREAD

**Issue by nkev** [gen2brain/malgo#8]
Is there any plan to update to Miniaudio v0.9.1? I think there are some breaking changes though.

**Comment by gen2brain** [comment]
Sure, will be updated, not sure when will that happen, as you noticed there are some breaking changes and some renaming have to be done.

**Comment by godsic** [comment]
@nkev I did a rough port here https://github.com/godsic/malgo

**Comment by gen2brain** [comment]
@nkev what are the rough parts? Can you send a PR if everything works as expected? I have some local copy where I tried to update to latest API and I failed but didn't have time to check all details.

**Comment by godsic** [comment]
@gen2brain 
- 0.9 introduced new features that are not ported to malgo at the moment;
- I am tracking dev branch for wasapi resampling/sample format control;
- alsa and wasapi backends work, others were not tested;
- capture and full duplex modes were not tested.

If that’s ok with you I can go ahead with making a PR.

**Comment by gen2brain** [comment]
Yes please, new features can wait a bit, but if it works on Linux and Windows it can be merged. If there are some issues after that they can be fixed later, much better then to be too much behind upstream lib.

**Comment by dlsniper** [comment]
I guess this can be closed now that #11 was merged?

**Comment by gen2brain** [comment]
Right, closing.
